# 主题基本配置
theme_style: geek # 极客风格

# 配色方案
colors:
  primary: "#00ff00" # 荧光绿
  secondary: "#1a1a1a" # 深灰
  accent: "#00ffff" # 青色

# 代码高亮
highlight:
  theme: "monokai" # 深色主题
  enable: true
  line_number: true
  wrap: true

# 功能开关
features:
  dark_mode: true # 暗色模式切换
  code_copy: true # 代码复制
  toc_sticky: true # 固定目录
  back_to_top: true # 返回顶部

# 响应式设计
responsive:
  mobile: 768px
  tablet: 1024px
  desktop: 1200px

menu:
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about

# 社交链接
social:
  github: 
  twitter: 
  email: 

# 主题颜色
theme_color:
  primary: "#2196f3"
  secondary: "#ffffff"
  background: "#f5f5f5"
  text: "#333333"

# 其他设置
show_toc: true
toc_depth: 3

# 页脚配置
footer:
  # 是否显示站点统计
  statistics: true
  # ICP备案信息
  icp: '@ddddddddd'
  # 页脚自定义文本
  custom_text: 'ddddddddd'

# 归档页面配置
archive_generator:
  per_page: 20
  yearly: true
  monthly: false
  order_by: -date